name: "Segnalazione Issue"
description: "Crea una nuova issue per segnalare un bug, una richiesta di miglioramento o un'altra problematica."
title: "[Issue] <Titolo della segnalazione>"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Grazie per aver aperto una nuova issue!
  - type: input
    id: summary
    attributes:
      label: "Descrizione breve"
      description: "Fornisci un riassunto chiaro e conciso del problema."
      placeholder: "Es. Errore nel login degli utenti"
    validations:
      required: true

  - type: textarea
    id: problem-details
    attributes:
      label: "Dettagli del problema"
      description: "Descrivi il problema nel dettaglio, includendo eventuali errori o comportamenti inattesi."
      placeholder: "Es. Quando provo a effettuare il login con credenziali corrette, il sistema mostra un errore 500."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Passaggi per riprodurre il problema"
      description: "Elenca i passaggi per riprodurre il problema."
      placeholder: |
        1. Aprire l'app
        2. Inserire username e password
        3. Cliccare su 'Login'
        4. Si verifica l'errore 500
    validations:
      required: false
